'use client';

import React from 'react';
import { useAuth } from '@/lib/auth-context';
import { Download, FileSpreadsheet, ShieldCheck } from 'lucide-react';
import { exportToXls, exportToPdf } from '@/lib/export-utils';
import { haptics } from '@/lib/haptics';

export default function AuditLogPage() {
  const { auditLogs, currentUser } = useAuth();

  const handleExportAuditPdf = () => {
    exportToPdf({
      filename: `AquaEarth_Audit_Trail_${new Date().toISOString().split('T')[0]}`,
      title: 'Enterprise Security & Compliance Platform Audit Trail',
      subtitle: `AquaEarth Consulting Limited — Sovereign System Audit Log | Generated by: ${currentUser.name}`,
      category: 'ENTERPRISE AUDIT TRAIL',
      summaryMetrics: [
        { label: 'Total Events', value: String(auditLogs.length) },
        { label: 'System Custodian', value: currentUser.name },
        { label: 'Unique Actors', value: String(new Set(auditLogs.map(l => l.actorName)).size) },
        { label: 'Audit Scope', value: 'Sovereign DB & RBAC' }
      ],
      columns: [
        { header: 'Timestamp (UTC+1)', key: 'timestamp', width: '130px' },
        { header: 'Actor / User', key: 'actorName' },
        { header: 'Action', key: 'action' },
        { header: 'Target Scope', key: 'targetType', format: (val, row) => `${val || ''} ${row.targetId ? `(#${row.targetId})` : ''}` },
        { header: 'Event Details', key: 'details' }
      ],
      data: auditLogs,
      signatories: [
        { role: 'SYSTEM AUDITOR', name: currentUser.name, title: `${currentUser.jobTitle || 'Compliance Officer'}` },
        { role: 'HEAD OF IT & CYBERSECURITY', name: 'Engr. Femi Adebayo', title: 'Chief Technology Officer' },
        { role: 'MANAGING CONSULTANT', name: 'Dr. Kaine Edike', title: 'Managing Consultant (MD / FNEC)' }
      ]
    });
    haptics.success();
  };

  const handleExportAuditXls = () => {
    exportToXls({
      filename: `AquaEarth_Audit_Trail_${new Date().toISOString().split('T')[0]}`,
      title: 'ENTERPRISE SECURITY & COMPLIANCE PLATFORM AUDIT TRAIL',
      subtitle: `AquaEarth Consulting Limited — Extracted by: ${currentUser.name}`,
      category: 'SECURITY AUDIT',
      metadata: {
        'Custodian': currentUser.name,
        'Total Events': String(auditLogs.length)
      },
      summaryMetrics: [
        { label: 'Total Events', value: auditLogs.length }
      ],
      columns: [
        { header: 'Event ID', key: 'id' },
        { header: 'Timestamp (UTC+1)', key: 'timestamp' },
        { header: 'Actor Name', key: 'actorName' },
        { header: 'Actor ID', key: 'actorId' },
        { header: 'Action Event', key: 'action' },
        { header: 'Target Type', key: 'targetType' },
        { header: 'Target ID', key: 'targetId' },
        { header: 'Details', key: 'details' }
      ],
      data: auditLogs
    });
    haptics.success();
  };

  const handleExportCsv = () => {
    haptics.selection();
    const headers = 'ID,Timestamp,Actor,Action,Target Type,Target ID,Details';
    const rows = auditLogs.map(l => [
      l.id,
      `"${l.timestamp}"`,
      `"${l.actorName.replace(/"/g, '""')}"`,
      l.action,
      l.targetType,
      l.targetId || '',
      `"${(l.details || '').replace(/"/g, '""')}"`
    ].join(','));
    const csvContent = [headers, ...rows].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `aquaearth_audit_log_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
            <ShieldCheck className="w-6 h-6 text-emerald-600" />
            <span>Platform Audit Trail</span>
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Immutable system activity log tracking access, role changes, project gates, and compliance events.
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleExportAuditPdf}
            className="flex items-center gap-1.5 px-3.5 py-1.5 bg-white dark:bg-white/10 border border-black/[0.08] dark:border-white/10 hover:bg-slate-50 dark:hover:bg-white/15 text-slate-700 dark:text-slate-200 font-semibold rounded-2xl text-xs shadow-2xs transition-all active:scale-[0.96] cursor-pointer"
            title="Download PDF Audit Report"
          >
            <Download className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
            <span>PDF Report</span>
          </button>

          <button
            onClick={handleExportAuditXls}
            className="flex items-center gap-1.5 px-3.5 py-1.5 bg-white dark:bg-white/10 border border-black/[0.08] dark:border-white/10 hover:bg-slate-50 dark:hover:bg-white/15 text-slate-700 dark:text-slate-200 font-semibold rounded-2xl text-xs shadow-2xs transition-all active:scale-[0.96] cursor-pointer"
            title="Download Excel Audit Log"
          >
            <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
            <span>Excel</span>
          </button>

          <button
            onClick={handleExportCsv}
            className="flex items-center gap-1.5 px-3.5 py-1.5 bg-white dark:bg-white/10 border border-black/[0.08] dark:border-white/10 hover:bg-slate-50 dark:hover:bg-white/15 text-slate-700 dark:text-slate-200 font-semibold rounded-2xl text-xs shadow-2xs transition-all active:scale-[0.96] cursor-pointer"
            title="Export CSV"
          >
            <Download className="w-3.5 h-3.5 text-slate-500" />
            <span>CSV</span>
          </button>
        </div>
      </div>

      {/* Table */}
      <div className="apple-glass-card rounded-3xl overflow-hidden border border-black/[0.06] dark:border-white/10">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50/60 dark:bg-white/[0.03] border-b border-black/[0.05] dark:border-white/[0.06] text-slate-400 dark:text-slate-500 font-semibold uppercase tracking-wider text-[10px]">
              <tr>
                <th className="px-5 py-3">Timestamp (UTC+1)</th>
                <th className="px-5 py-3">Actor</th>
                <th className="px-5 py-3">Action</th>
                <th className="px-5 py-3">Target</th>
                <th className="px-5 py-3">Details</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-black/[0.04] dark:divide-white/[0.06] font-medium">
              {auditLogs.map((log) => (
                <tr key={log.id} className="hover:bg-black/[0.02] dark:hover:bg-white/[0.03] transition-colors">
                  <td className="px-5 py-3 text-slate-400 dark:text-slate-500 font-mono text-[11px] tnum">
                    {log.timestamp}
                  </td>
                  <td className="px-5 py-3 font-semibold text-slate-900 dark:text-white">
                    {log.actorName}
                  </td>
                  <td className="px-5 py-3">
                    <span className="px-2 py-0.5 rounded-lg font-mono text-[10px] font-semibold bg-slate-100 dark:bg-white/10 text-slate-700 dark:text-slate-300 border border-black/[0.06] dark:border-white/10">
                      {log.action}
                    </span>
                  </td>
                  <td className="px-5 py-3 text-slate-600 dark:text-slate-300 font-semibold">
                    {log.targetType} {log.targetId && `(#${log.targetId})`}
                  </td>
                  <td className="px-5 py-3 text-slate-600 dark:text-slate-400">
                    {log.details}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
